org: utec
service: api-productos

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::385301667309:role/LabRole
  environment:
    TABLE_NAME: ${sls:stage}-t_productos

functions:
  crearProducto:
    handler: producto.crearProducto
    events:
      - http:
          path: /productos/create
          method: post
          cors: true
          integration: lambda

  eliminarProducto:
    handler: producto.eliminarProducto
    events:
      - http:
          path: /productos/delete
          method: delete
          cors: true
          integration: lambda

  obtenerProducto:
    handler: producto.obtenerProducto
    events:
      - http:
          path: /productos/get
          method: get
          cors: true
          integration: lambda

  actualizarProducto:
    handler: producto.actualizarProducto
    events:
      - http:
          path: /productos/update
          method: put
          cors: true
          integration: lambda

  listarProductos:
    handler: producto.listarProductos
    events:
      - http:
          path: /productos/list
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    TablaProductos:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenantID
            AttributeType: S
          - AttributeName: productoID
            AttributeType: S
          - AttributeName: nombre
            AttributeType: S
          - AttributeName: precio
            AttributeType: N
          - AttributeName: categoriaID
            AttributeType: S
        KeySchema:
          - AttributeName: tenantID
            KeyType: HASH
          - AttributeName: productoID
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        LocalSecondaryIndexes:
          - IndexName: NombreIndex
            KeySchema:
              - AttributeName: tenantID
                KeyType: HASH
              - AttributeName: nombre
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        GlobalSecondaryIndexes:
          - IndexName: PrecioIndex
            KeySchema:
              - AttributeName: tenantID
                KeyType: HASH
              - AttributeName: precio
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: CategoriaIndex
            KeySchema:
              - AttributeName: tenantID
                KeyType: HASH
              - AttributeName: categoriaID
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
